# 返回值与错误处理

## Option辅助函数

*   `unwrap()`

        let mut s = String::from("hello");
        let p1 = s.pop().unwrap();
        println!("{}", p1); //o
        let p2 = s.pop();
        println!("{:?}", p2); //Some('l')
*   `unwrap_or()` 提供默认值

        fn main() {
            let r = div(10, 0).unwrap_or(0.0);
            println!("{}", r)
        }

        fn div(a: i32, b: i32) -> Option<f64> {
            if b != 0 {
                Some(a as f64 / b as f64)
            } else {
                None
            }
        }
*   `is_none()` && `is_some()`

        let v = [1, 2, 3];
        if v.get(1).is_some() {
            println!("{}", v[1]);
        }
        if !v.get(0).is_none() {
            println!("{}", v[0]);
        }

## 错误

*   可恢复错误，使用`Result<T,E>`

        //失败的时候返回String类型
        fn div(a: i32, b: i32) -> Result<f64, String> {
            if b != 0 {
                Ok(a as f64 / b as f64)
            } else {
                Err("b can not zero".to_string())
            }
        }

        //统一错误输出
        enum MathError {
            DivisionByZero,
            NegativeSquareRoot,
        }
        fn div(a: i32, b: i32) -> Result<f64, MathError> {
            if b != 0 {
                Ok(a as f64 / b as f64)
            } else {
                Err(MathError::DivisionByZero)
            }
        }
*   不可恢复错误，使用`panic!`

    *   `panic` 时的两种终止方式

        *   栈展开(unwinding) (默认)：Rust 会回溯栈上数据和函数调用，因此也意味着更多的善后工作，好处是可以给出充分的报错信息和栈调用信息，便于事后的问题复盘
        *   直接终止 (abort)：不清理数据就直接退出程序，善后工作交与操作系统来负责
        *   对于绝大多数用户，使用默认选择是最好的，但是当你关心最终编译出的二进制可执行文件大小时，那么可以尝试去使用直接终止的方式，例如下面的配置修改 `Cargo.toml` 文件，实现在 `release` 模式下遇到 `panic` 直接终止

                [profile.release]
                panic = 'abort'

            ```bash
            RUST_BACKTRACE=1 cargo run --release
            ```

### Result辅助函数

*   `unwrap()`
*   `unwrap_or()` 提供默认值
*   `expect()`
*   `map()` 对`Ok`的值进行转换

        let line = "1\n2\n3\n4\n";
        for num in line.lines() {
            let r = num.parse::<i32>().map(|i| i * 2).unwrap();
            println!("{}", r);
        }
*   `map_err()` 对`Err`进行转换

        fn x() -> Result<(), String> {
            let f = File::open("hello.txt").map_err(|e: std::io::Error| format!("{e}"));
            match f {
                Err(e) => Err(e),
                Ok(_) => Ok(()),
            }
        }

## 错误传播

    fn read_username_from_file() -> Result<String, std::io::Error> {
        let mut s = String::new();

        File::open("hello.txt")?.read_to_string(&mut s)?;

        Ok(s)
    }


    fn read_username_from_file() -> Result<String, String> {
        let mut s = String::new();

        File::open("hello.txt")
            .map_err(|e| format!("{e}"))?
            .read_to_string(&mut s)
            .map_err(|e| format!("{e}"))?;

        Ok(s)
    }

## 练习

    fn call(a: i32, b: i32) -> Result<f64, String> {
        let r = divide(a, b).unwrap_or(a as f64 / 1.0);
        let s = sqrt(r).map_err(|e| format!("NegativeSquareRoot"))?;
        Ok(s)
    }
    fn divide(a: i32, b: i32) -> Option<f64> {
        if b != 0 {
            Some(a as f64 / b as f64)
        } else {
            None
        }
    }
    pub enum MathError {
        DivisionByZero,
        NegativeSquareRoot,
    }
    fn sqrt(x: f64) -> Result<f64, MathError> {
        if x < 0.0 {
            Err(MathError::NegativeSquareRoot)
        } else {
            Ok(x.sqrt())
        }
    }

